plugins:
  - jekyll-relative-links
theme: jekyll-theme-dinky
title: fun with big data

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - bigdata_intro.md
  - characteristics_of_big_data.md
